/*


> Zp:=pAdicQuotientRing(p,4);  
> Zq<a>:=UnramifiedExtension(Zp,3);   
> Zq;
Unramified extension of Quotient of the 5-adic ring modulo the ideal generated by 
5^4 modulo x^3 + 3*x + 3
> a;
a
> Fq<aa>:=ResidueClassField(Zq);
> TeichmuellerLift(aa,Zq);     
85*a^2 - 69*a + 35



*/

function CanLift(j,n)
    // j in a finite field, n the precision
    F:=Parent(j);
    p:=Characterisic(F);
    k:=Degree(F); // q:=p^k

    Zq:=UnramifiedExtension(pAdicQuotientRing(p,n+1),k);
    Fq:=ResidueClassField(Zq);

    J:=TeichmullerLift(Fq!j,Zq);

    if n eq 0 then
        return J;
    end if;

end function;
